### ISSUE TITLE
Error with composer when installing.

### ISSUE THREAD

**Issue by Porcar** [GrahamCampbell/Laravel-Dropbox#11]
Is there a way to add the providers before doing composer update? (it gets bothersome when working with repositories, to have to delete both providers, do a composer update, and then add them back in. 

What i mean is, i want to download my repository and just do a composer install, instead of having to open the config/app.php comment :

`'GrahamCampbell\Dropbox\DropboxServiceProvider'`

and 

`'Dropbox' => 'GrahamCampbell\Dropbox\Facades\Dropbox'`

so i can do a composer install or update.

The error you get if you do a composer update with those lines not commented is 
"class 'GrahamCampbell\Dropbox\DropboxServiceProvider' not found"

note: yes..i added the 
```
{
    "require": {
        "graham-campbell/dropbox": "^3.0"
    }
}
```

to composer.json

Thanks in advance.

**Comment by vinkla** [comment]
No, you have to install it with Composer first.

**Comment by GrahamCampbell** [comment]
Please reread my readme.
