### ISSUE TITLE
app configuration. 

### ISSUE THREAD

**Issue by ctf0** [GrahamCampbell/Laravel-Dropbox#12]
as described in https://github.com/GrahamCampbell/Laravel-Dropbox/blob/master/config/dropbox.php
we only have >
```php
'token'  => 'your-token',
'app'    => 'your-app',
```

but in the app console i have 3 keys (App key, App secret, access token) so which ones should i add ?

**Comment by GrahamCampbell** [comment]
You need to go through the oauth process by yourself to generate the token.

**Comment by ctf0** [comment]
okay, so the first 2 are `token = key , app = secret` ?
