### ISSUE TITLE
Class dropbox does not exist

### ISSUE THREAD

**Issue by anandatheerthan** [GrahamCampbell/Laravel-Dropbox#13]
Have implemented all steps as mentioned but getting error 
ReflectionException in Container.php line 741:
Class dropbox does not exist

can you please help.

**Comment by GrahamCampbell** [comment]
Looks like the service provider is not properly registered. Please make sure you regen your config cache.

**Comment by anandatheerthan** [comment]
can you please tell me how to regen the cache. Sorry for the noob question.

**Comment by GrahamCampbell** [comment]
Feel free to have a read through Laravel's docs: https://laravel.com/docs/5.2/configuration#configuration-caching.
