### ISSUE TITLE
Dropbox API v2

### ISSUE THREAD

**Issue by dudheit** [GrahamCampbell/Laravel-Dropbox#15]
I was wondering whether this package depends on the [deprecated Dropbox API v1](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) and if so, if there are any plans to move to API v2.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. If dropbox upgrade their PHP SDK to the new library, than this library will follow as a consequence.
