### ISSUE TITLE
PHP Dropbox API v2

### ISSUE THREAD

**Issue by ManuDoni** [GrahamCampbell/Laravel-Dropbox#17]
Since Dropbox has deprecated the v1 API (https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/) and they won't release a v2 official PHP SDK (https://www.dropboxforum.com/hc/en-us/community/posts/207429906-PHP-SDK-for-API-v2), will this package implements some of the unofficial repos listed [here] (https://www.dropbox.com/developers/documentation/communitysdks)?

**Comment by GrahamCampbell** [comment]
No plans for that at the moment. Waiting for Dropbox to update their own sdk.

**Comment by ManuDoni** [comment]
Thanks, very quick!
