### ISSUE TITLE
Overwrite if the file is already present 

### ISSUE THREAD

**Issue by grab76** [GrahamCampbell/Laravel-Dropbox#19]
First I want to say thank you for your work and for this extension.

I have a question : 
Is it possible to overwrite a file on dropbox if the file is already present ?
If I upload twice times a file, the file will be rename "my_file (1).extension".
Do you have a WriteMode:: that allows to overwrite if the file is already present on DropxBox ?

**Comment by GrahamCampbell** [comment]
No idea I'm afraid. This package is just a wrapper.
