### ISSUE TITLE
Missing OAuth support

### ISSUE THREAD

**Issue by thunderrabbit** [GrahamCampbell/Laravel-Dropbox#2]
In your code, I don't see anything related to OAuth.  The existing code is beautiful; your [docs](http://docs.grahamjcampbell.co.uk/) are amazing, but I can't get even the first of the [Real Examples](https://github.com/GrahamCampbell/Laravel-Dropbox#real-examples) to work.

```php
Dropbox::createFolder('foo');
```

fails, saying "The given OAuth 2 access token doesn't exist..."

Do you have an example Laravel app which uses OAuth and your Dropbox library?

**Comment by SaadAhmed13** [comment]
Hi Graham,
Is it possible to create connection for each user dynamically within in the php after getting their oAuth token instead of manipulaing the app config file?

**Comment by GrahamCampbell** [comment]
Yeh. You can "set" config at runtime. See the laravel docs for this. NB, it won't be persisted to the actual config file, it'll just be persisted for the current request.

**Comment by SaadAhmed13** [comment]
Thanks, I am currently storing tokens of each user in database so i plan on modifying the main connection properties at runtime for each user something like: Auth::User()->getToken() and then i want to set the main connection token to this at runtime.

**Comment by Nulimitz** [comment]
I would really like to see a basic tutorial on using this. Just to get some ideas. Saad, couldn't you store that token temporarily as a cookie and then create the connection form that ?

**Comment by GrahamCampbell** [comment]
> I would really like to see a basic tutorial on using this. 

Ask dropbox to do this, as ultimately, we're using their package.

**Comment by GrahamCampbell** [comment]
I don't have any time to add anything more to this package atm, though all authentication methods ARE supported by this package.

**Comment by Nulimitz** [comment]
I was more refering to your dropbox package just a general setup and usage.
Some example. Guess i can bypass it too and go with phoacademy's tutorial.
Thanks anyways.
