### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by nickstock** [GrahamCampbell/Laravel-Dropbox#20]
Im a bit new to this so excuse if not an issue but when i ran $ composer require graham-campbell/dropbox composer installed something called graham-campbell-manager so the service provider and facade caused errors when attempting vendor-publish.
I guess its just a linking issue with composer. anyway i edited the composer file and ran composer update which sorted it out.

**Comment by GrahamCampbell** [comment]
How do you mean. The manager package is absolutely required, and should not be removed?

**Comment by nickstock** [comment]
in that case let me put it a different way.. when i ran composer require graham-campbell/dropbox it did not install the dropbox files, my ide reported invalid namespace for the service provider and the facade.
when i added the require into composer.json manually it all installed.

**Comment by GrahamCampbell** [comment]
Running composer require is exactly the same as adding the require to the composer.json.

**Comment by GrahamCampbell** [comment]
In any case, if there is a bug here, it's related to composer.

**Comment by GrahamCampbell** [comment]
Perhaps you ran require from the wrong directory?
