### ISSUE TITLE
uploadFile issue

### ISSUE THREAD

**Issue by mostafa6765** [GrahamCampbell/Laravel-Dropbox#21]
Please give a uploadFile sample . 

ClientTest.php has more than 3 types uploadFile but I can't access . 

$fp = fopen($localPathSource, "rb");
        $up = $this->client->uploadFile($remotePath, dbx\WriteMode::add(), $fp);

please add uploadFile system with laravel.

**Comment by GrahamCampbell** [comment]
Sorry, I don't control the underlying sdk.
