### ISSUE TITLE
Dropbox API v2

### ISSUE THREAD

**Issue by ZiaSean** [GrahamCampbell/Laravel-Dropbox#22]
Graham, 
Doing a bit of googling earlier, I tripped across this:
https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/
...which I remember getting an email about last year, but just realized it specifies "we’ll be turning off API v1 a year from now, on **6/28/2017**" -- in just a couple weeks.

Any plan to update this project to v2, or do I need to be planning to do some replacement work?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. I don't plan to update this project, since we now have various other packages that integrate dropbox v2 API with flysystem, for example.

**Comment by GrahamCampbell** [comment]
(in fact, my laravel flysystem library will do this, starting from the next release)
