### ISSUE TITLE
Connection [] not configured.

### ISSUE THREAD

**Issue by kelvinrolex** [GrahamCampbell/Laravel-Dropbox#3]
i am trying to use the GrahamCampbell/Laravel-Dropbox, i have done all the configurations and also set the dropbox token and app in dropbox config file, but when i run Dropbox::createFolder('foo'); just to test if it is working, i get an error message saying "Connection [] not configured" and the default connection is set to main. I am using Laravel 5.
![error fw](https://cloud.githubusercontent.com/assets/10676937/5883875/cc0f06d4-a36f-11e4-8962-b8309924297f.png)

**Comment by GrahamCampbell** [comment]
Have you correctly installed the orchestral config component, and published your config, and added your api key?

**Comment by kelvinrolex** [comment]
Ok i think i skipped the Orchestral config component during installation, lemme install it...

**Comment by kelvinrolex** [comment]
Hello Graham,
I was able to get the installation right but i have a problem using the uploadFile(string $path, WriteMode $writeMode, string $data) method, the problem is i don't know the WriteMode, please help me list out the WriteMode. Thanks

**Comment by kelvinrolex** [comment]
Got what i was looking for...Thanks
