### ISSUE TITLE
How to get my url dropbox file?

### ISSUE THREAD

**Issue by donnygunawan** [GrahamCampbell/Laravel-Dropbox#6]
hello,
I has succeed upload into dropbox,
Then I need url for my imgsrc,
how can I get it?

**Comment by GrahamCampbell** [comment]
I'd have to assume it's documented in https://www.dropbox.com/developers-v1/core/start/php, but I'm no expert, so I don't really know.

**Comment by GrahamCampbell** [comment]
My package literally wraps dropbox's library and makes it work quickly in laravel with the added bonus of multiple connections through a manager class.

**Comment by brunocascio** [comment]
+1
