### ISSUE TITLE
Example for uploading files

### ISSUE THREAD

**Issue by blyleven** [GrahamCampbell/Laravel-Dropbox#7]
Hi Graham, 

Thanks for your great package. However I can create folders within Dropbox with your package, I can't seem to get uploading a pdf file working. 

Can you give me an example? 

Thanks!
Michael

**Comment by GrahamCampbell** [comment]
Please see dropbox's own docs.

**Comment by afifzi** [comment]
How to use class Dropbox/WriteMode because i try to upload file need method WriteMode::add() but I can't use GrahamCampbell\Dropbox\Facades\Dropbox\WriteMode; ?
