### ISSUE TITLE
Create a connection "on-the-fly" ?

### ISSUE THREAD

**Issue by Tailzip** [GrahamCampbell/Laravel-Dropbox#9]
Hi,

I'm looping over multiple users API access_token, to perform actions on each user Dropbox account, but I can't create a connection with a custom config "on the fly". Is that even possible?

I tried to play with the `'extend'` method without success...

Ultimately, I'd like to do something like this :
```php
Dropbox::connection([
 'token' => $user_access_token,
 'app' => 'myapp/0.1'
])->getAccountInfo();
```

Thanks!

**Comment by GrahamCampbell** [comment]
Just use the dropbox factory class and call the make method with your config. ;)

**Comment by GrahamCampbell** [comment]
Similar to https://github.com/GrahamCampbell/Laravel-DigitalOcean/issues/6.

**Comment by GrahamCampbell** [comment]
https://github.com/GrahamCampbell/Laravel-Dropbox/blob/master/tests/DropboxFactoryTest.php

**Comment by GrahamCampbell** [comment]
Those tests show the idea, but, in code, don't write `new DropboxFactory();`, just resolve it from the ioc container.
